- module-domain/src/main/java/com/mile/moim/domain/Moim.java
- Closes #11 
1. 기존 Moim 테이블에서 id가 String 변수여서 발생하던 실행 오류를 값 타입을 Long으로 변경하면서 해결했습니다 
- 같이 작업한 거라서 리뷰할 때 꼼꼼하게 하지 못했는데 이게 문제였네요! 앞으로는 리뷰 꼼꼼히 할게요 😅 
- PR 올리기 전 해야할 것
- 빌드, 실행 해보고 오류 없는지 확인합시다!
- 커밋하기 전에 해야할 것
- ctrl + alt + o -> 미사용 import 삭제
- ctrl + alt + l -> 코드 포맷팅
> #11 [feat] DDL Exception 해결

- module-api/src/main/java/com/mile/controller/post/PostController.java
- module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/comment/domain/Comment.java
- module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/comment/service/dto/CommentResponse.java
- module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/post/service/dto/CommentListResponse.java
- module-domain/src/main/java/com/mile/writerName/serivce/WriterNameService.java
- Closes #25 
1. 스웨거 작업해주었습니다!
2. `Comment` 내부 연관관계를 `User`에서 `WriterName`으로 변경했습니다!
- 기존에 실명 <-> 익명 제도여서 User로 엮어뒀었는데 필명 <-> 익명제도로 변경되었고, 이 모임에 대한 권한이 있는지 확인하는 플로우가 자주 사용되니 `WriterName`으로 변경하는게 적합하다고 판단했습니다! 혹시 의견있으면 남겨주세요!
3. `PostAuthenticateService`와 `PostService` 분리
- `CommentService`에서 해당 post에 대한 댓글 권한이 있는지 확인하는 플로우에서 `PostService` 를 참조해야 했는데, 이미 `PostService`에서 `CommentService`를 참조하고 있어순환 참조 문제가 발생하고, 또한 PostService의 역할이 커지는 것 같아 검증과 관련된 메소드는 `PostAuthenticateService`를 따로 두어 역할을 분리해주었습니다.
- 아자잣!
> #25 [feat] GET - 글 해당 댓글 리스트 조회 구현

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/authentication/CustomJwtAuthenticationEntryPoint.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/serivce/MoimService.java
- module-domain/src/main/java/com/mile/moim/serivce/dto/MoimAuthenticateResponse.java
- Closes #30 
1. jwt 토큰으로 인증을 하고 security filter chain에서 걸릴 경우 에러 메시지 없이 빈 화면이 발생하는 것을 EntryPoint에서 커스텀 해주었습니다!
2. 마련되어 있는 메서드 활용하여 구현했습니다! 
3. 스웨거 작성했습니다!
1. 
2. 
3.
- 코드 이상한 점 알려주세요!
> #30 [feat]  모임에 대한 권한 확인

- module-api/src/main/java/com/mile/controller/post/PostController.java
- module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/build.gradle
- module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/curious/repository/CuriousRepository.java
- module-domain/src/main/java/com/mile/curious/serivce/CuriousService.java
- module-domain/src/main/java/com/mile/post/domain/Post.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-external/src/main/java/com/mile/aws/utils/S3Service.java
- Closes #41 
1. 스웨거 작성하였습니다
2. Post 엔티티에 boolean containPhoto 값 추가했습니다.
3. s3 delete 모듈도 연동했습니다.
4. 삭제할 때 댓글, 궁금해요 엔티티도 함께 삭제해줘야 하기 때문에 함께 삭제 구현했습니다.
- 코드 수정사항 있으면 알려주세요!
> #41 [feat] 글 삭제 구현

- module-domain/build.gradle
- module-domain/src/main/java/com/mile/moim/service/dto/MoimMostCuriousPostResponse.java
- module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java
- Closes #88 
1. DTO 내부에서 전체 content를 받아온 후 html 파싱을 진행한 뒤 길이를 200자(웹-서 회의 후 결정)로 substring을 추출했습니다.
-
> #88 [feat] html 태그 파싱 및 길이 제한 수정

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/TemporaryPostExistResponse.java
- module-domain/src/main/java/com/mile/post/repository/PostRepository.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryImpl.java
- module-domain/src/main/java/com/mile/post/service/PostTemporaryService.java
- Closes #90 
1. PostService 임시저장글 관련 로직은 분리했습니다!
2. QueryDsl 사용했습니다! 
3. 카카오 소셜 로그인 플로우 확인 완료 -> redirect uri 최종 수정
-
> #90 [feat] 임시 저장 글 존재 여부 API 구현

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryCustom.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryCustomImpl.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/BestMoimInfoResponse.java
- module-domain/src/main/java/com/mile/moim/service/dto/BestMoimListResponse.java
- module-domain/src/main/java/com/mile/moim/service/dto/BestMoimPostResponse.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimMostCuriousPostResponse.java
- module-domain/src/main/java/com/mile/post/repository/PostRepository.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryImpl.java
- module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java
- Closes #84 
베스트 활동 모임 및 모임별 글 조회를 구현하였습니다!
1. query dsl 를 사용하여 글 개수가 많은 모임을 리턴하고, 모임 내 최신순 글을 리턴하였습니다.
2. 순환 참조 해결을 위해 postService에 있던 메소드를 postGetService로 변경하였습니다.
3. Jsoup를 이용하여 도짜미가 구현해준 메서드로 html 태그 제거를 하였는데 content의 길이가 200 미만인 경우에 대해서 에러가 발생해서, 길이를 검사하는 로직을 추가했습니다.
> #84 GET - 베스트 활동 모임 및 모임별 글 조회

- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/post/service/dto/TemporaryPostGetResponse.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- module-domain/src/main/java/com/mile/topic/service/dto/ContentWithIsSelectedResponse.java
- Closes #92 
클라분들께서 글감 리스트와 해당 글감이 선택되었는지 여부를 반환해 달라고 요청하셔서 해당 로직을 구현하였습니다.
> #92 [refactor] GET - 임시저장된 글 조회 시 글감 리스트 반환

- module-domain/src/main/java/com/mile/moim/domain/Moim.java
- module-domain/src/main/java/com/mile/writerName/repository/WriterNameRepositoryImpl.java
- Closes #108 
1. 현재 db에서 moim의 owner가 빈 값이었는데 writername과 owner가 같은 것을 join하므로 user의 모든 테이블의 join되었습니다! 그래서 non unique result -> 쿼리문에 한개 이상의 결과가 나오는 예외가 발생했습니다!
2. 모임 정보에서 필명을 가져오는데 writerName과 연관관계가 있는게 맞다고 판단되어 owner를 writername 객체와 연관관계를 정해주었습니다!
3. where문을 작성해서 한개의 결과만 return 하도록 하였습니다!
- db도 수정하겠습니다!
> #108 [fix] 연관관계 변경 및 쿼리문 재작성

- module-domain/src/main/java/com/mile/post/repository/PostRepositoryImpl.java
- Closes #119 
1. 아래 쿼리문 기준으로 queryDsl로 마이그레이션했습니다!
```java
SELECT post.*
FROM post
JOIN topic t ON t.id = post.topic_id
JOIN moim m ON t.moim_id= m.id
WHERE m.id = :moim_id
ORDER BY post.curious_count DESC
LIMIT 2;
```
-
> #119 [fix] 글 궁금해요 기준 정렬 쿼리문 수정

- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/writerName/service/dto/WriterNameResponse.java
- Closes #123 
1. 글 생성 및 임시저장 후 저장 API 반환 DTO에서 postId를 함께 넘겨 주도록 변경하였습니다.
2. 엔터티를 저장하고 즉시 플러시하여 데이터베이스에 변경 사항을 반영 한 후 post의 getId를 할 수 있도록, saveAndFlush를 사용하였습니다.
> #123 [fix] 글 생성 및 임시저장 후 저장 API 반환 DTO 변경

- module-api/src/main/java/com/mile/controller/comment/CommentController.java
- module-api/src/main/java/com/mile/controller/comment/CommentControllerSwagger.java
- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-api/src/main/java/com/mile/controller/post/PostController.java
- module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
- module-common/src/main/java/com/mile/authentication/PrincipalHandler.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/utils/SecureUrlUtil.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- Closes #132 
- 기존에 사용하던 principal.getName은 `NullPointerException` 을 발생시킬 수 있어 SecurityContenxt에서 Principal을 가져오는 방식으로 변경했습니다. 만일 로그인을 하지 않은 상태로 API 요청을 하게 되면 anonymousUser가 되기 때문에 이를 검사하고 체크해주는 로직으로 변경했습니다.
- 또한, url인코딩 로직을 분리하고 이를 사용했습니다! 
- 아자자!
> #132 [feat] principal null exception 해결 및 secure url 로직 분리

- module-domain/src/main/java/com/mile/post/service/dto/PostPutRequest.java
- Closes #146 
anonymous를 boolean 인데, 이에 대한 validation을 NotEmpty로 하고 있어서 오류가 발생하였습니다. 
```java
HV000030: No validator could be found for constraint 'jakarta.validation.constraints.NotEmpty' validating type 'java.lang.Boolean'. Check configuration for 'anonymous'
```
validation을 NotNull로 변경하였습니다
> #146 [fix] boolean 값에 대해 NotNull로 변경

- module-api/src/main/java/com/mile/ApiApplication.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-domain/src/main/java/com/mile/recommend/service/RecommendService.java
- Closes #152 
1. Application에 EnableScheduling 추가
2. 추천 글감 받아오는 로직 수정
-
> #152 [fix] 스케줄링 관련 버그 해결

- module-domain/src/main/java/com/mile/comment/service/dto/CommentResponse.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- Closes #156
userId로 비교를 하고 있었는데, writerNameId로 비교하여 반환하도록 변경하였습니다!
> #156 [fix] 댓글리스트 반환값 버그 해결

- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- Closes #195 
1. 내용
해당 글감의 글이 존재하지 않는 경우 기존에는 예외처리를 하고 있었으나,
클라의 요청에 따라 빈 배열 반환으로 변경하였습니다
-
> #195 [refactor] 해당 글감의 글이 존재하지 않는 경우 빈 배열 반환

- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryImpl.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- Closes #197 
글 모임 뷰 - 글감별 글 리스트,
메인 뷰 - 베스트 모임 글 리스트에서
임시저장글이 조회되는 버그를 발견하고 해결하였습니다
-
> #197 [fix] 임시저장글이 글 리스트에서 조회되는 에러 해결

- module-api/src/main/java/com/mile/controller/post/PostController.java
- module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
- module-domain/src/main/java/com/mile/post/domain/Post.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/post/service/PostUpdateService.java
- Closes #207 
1. 람다식 수정
2. API 엔드포인트 수정
3. 서비스 로직 분리
4. 기존에 updatePost에 의미없는 isTemporary 값을 받아오는 것을 setTemporary 메서드로 분리한 후, updatePost를 순수하게 update만 할 수 있게 유지했습니다.
- 우선 수정 API 위주로만 보았는데 고쳐야할 부분이 다른 데에도 많네요! 😅
> #207 [refactor] 글 수정 API 엔드포인트 수정 및 서비스 분리

- module-api/src/main/java/com/mile/controller/post/PostController.java
- module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
- module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
- module-domain/src/main/java/com/mile/curious/repository/CuriousRepository.java
- module-domain/src/main/java/com/mile/post/service/PostDeleteService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- Closes #211 
1. ResponseEntity 추가
2. 기존에 글 삭제를 진행하면서 관련 데이터를 삭제하던 쿼리문의 최대 개수는 무한대였습니다! 
이를 batch delete 방식을 선택하여 `@Query`를 사용하여 쿼리문을 최대 3개로 줄였습니다! 
-
> #211 [refactor] 글 삭제 api 리팩토링

- module-domain/src/main/java/com/mile/comment/domain/Comment.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/comment/service/dto/CommentResponse.java
- module-domain/src/main/java/com/mile/post/service/dto/CommentCreateRequest.java
- Closes #247 
1. POST 엔드포인트 수정 > Request Body에 boolean값 추가
2. GET 엔드포인트 로직 수정 -> 엔드포인트 자체는 수정할 요소가 없어서 name 리턴하는 함수 만들어서 수정했습니다
-
> #247 [feat] 댓글 등록시 익명 여부 POST & 댓글 조회시 익명 & 필명 나눠서 조회

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimNameConflictCheckResponse.java
- Closes #258 
1. exists 를 활용하여 글모임 이름 중복확인 GET API를 구현하였습니다!
> #258 [feat] 글모임 이름 중복확인 GET API 구현

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/domain/Moim.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimInfoModifyRequest.java
- Closes #261 
1. 도메인 로직 구현
2. 기존 중복체크 API URI 변경
-
> #261 [feat] 글모임 정보 수정 API 구현

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimWriterNameListGetResponse.java
- module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- module-domain/src/main/java/com/mile/writername/service/dto/WriterNameInfoResponse.java
- Closes #272
관리자페이지 멤버 리스트 조회를 구현하였습니다!
기존에 글감 리스트 조회를 구현할 때와 유사하게 
총 멤버 수와 멤버 정보 리스트를 리턴하도록 구현했습니다.
그런데 클라에서 총 페이지 개수 정보가 필요하다는 걸 깨달아서
Page객체의 getTotalPages 메소드를 이용해서 총 페이지 개수도 함께 리턴했습니다.
(글감 리스트 조회에도 요 부분 추가하겠습니다!)
> #272 [feat] 관리자페이지 멤버 리스트 조회 구현

- module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
- module-api/src/main/java/com/mile/controller/writername/WriterNameControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameDeleteService.java
- Closes #271
1. 관리자 페이지 멤버 삭제 로직을 구현했습니다!
1. MoimService <-> WriterNameService 간의 순환 참조가 발생해서, 삭제 로직을 WriterNameDeleteService로 분리하였습니다.
2. 기존에 엔드포인트를 /moim/:moimId/writerName/:writerNameId로 하였는데, 모임 아이디를 받을 필요가 없어서 엔드포인트를 변경하였습니다!
> #271 [feat] 관리자페이지 멤버 삭제 

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimTopicInfoListResponse.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimTopicInfoResponse.java
- module-domain/src/main/java/com/mile/topic/repository/TopicRepository.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- Closes #257
관리자페이지 글감 LIST 조회 API 를 구현하였습니다!
1. getAuthenticateOwnerOfMoim 메서드로 유저 정보가 관리자인지 확인하고,
2. 해당 모임의 전체 글감 수 조회
3. 해당 모임의 해당 페이지의 글감 리스트 조회 
의 로직으로 구성되었습니다!
JPA Pageable로 페이지네이션을 구현하였습니다!
페이지당 글감은 4개, 최신순으로 조회했습니다.
추가 ) 총 페이지 개수도 리턴하도록 변경하였습니다!
> #257 [feat] 관리자페이지 글감 LIST 조회

- module-api/src/main/java/com/mile/controller/topic/TopicController.java
- module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/post/service/PostDeleteService.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- module-domain/src/main/java/com/mile/topic/repository/TopicRepository.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- module-domain/src/main/java/com/mile/writername/domain/WriterName.java
- Closes #270
1. 글감 삭제 로직을 구현하였습니다!
2. 글 삭제 버그를 발견하여 수정했습니다.
- 글 삭제를 할 때, 해당 글에 대한 '궁금해요'들도 삭제됩니다.
- '궁금해요'들을 삭제하면서, 해당 글을 작성한 작가의 궁금해요수(totalCuriousCount) 도 감소시켜주어야 하는데, 해당 로직이 빠져 있어 추가했습니다.
```java
private void deleteRelatedData(
final Post post
) {
if (post.isContainPhoto()) {
deleteS3File(post.getImageUrl());
}
// 추가한 부분
WriterName writerName = post.getWriterName();
writerName.decreaseTotalCuriousCountByPostDelete(post.getCuriousCount());
curiousService.deleteAllByPost(post);
commentService.deleteAllByPost(post);
}
```
글감 삭제 로직은
1. 글감이 하나 남아있는 경우 예외처리
2. 글감에 대한 삭제 시 해당 글감의 글 삭제
- 글을 작성한 작가의 궁금해요 개수 차감
- 글에 대한 궁금해요 삭제
- 글에 대한 댓글 삭제
로 이뤄집니다!
> #270 [feat] 관리자페이지 글감 삭제 구현

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/domain/Moim.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimCreateRequest.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimCreateResponse.java
- module-domain/src/main/java/com/mile/moim/service/dto/TopicCreateRequest.java
- module-domain/src/main/java/com/mile/moim/service/dto/WriterMemberJoinRequest.java
- module-domain/src/main/java/com/mile/topic/domain/Topic.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- Closes #273
모임 생성 API를 구현하였습니다.
1. Request를 바탕으로 모임을 우선 생성하고,
2. 모임을 생성한 유저와 생성된 모임을 바탕으로 운영자 필명 생성
3. 초대링크 생성
4. 첫 글감 생성
의 순서로 로직을 구현하였습니다!
> #273 [feat] 모임 생성 API 구현

- module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
- module-domain/src/main/java/com/mile/comment/service/CommentGetService.java
- module-domain/src/main/java/com/mile/post/repository/PostRepository.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- module-domain/src/main/java/com/mile/writername/service/dto/WriterNameInfoResponse.java
- Closes #290 
1. 내용
멤버 리스트 조회에서, 멤버의 게시물 수와 댓글 수를 리턴하는 것으로 변경되어서 해당 부분을 구현했습니다
- writerNameService와 commentService간 순환참조 문제가 발생하여 commentGetService로 댓글 개수 조회 메서드를 분리하였습니다
> #290 [feat] 멤버 리스트 조회 변경 사항 반영

- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/post/service/PostCreateService.java
- module-domain/src/main/java/com/mile/post/service/PostDeleteService.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- Closes #286 
1. 기존에 흩어져 있던 post 관련 책임을 분리하였습니다.
2. 모임과 사용자에 해당하는 임시 저장 글이 있을 시 삭제하는 로직을 구현했습니다.
-
> #286 [feat] 임시저장 글 생성 시 삭제 로직 반영

- module-api/src/main/java/com/mile/controller/comment/CommentController.java
- module-api/src/main/java/com/mile/controller/comment/CommentControllerSwagger.java
- module-common/src/main/java/com/mile/config/web/WebConfig.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-common/src/main/java/com/mile/resolver/reply/ReplyIdPathVariable.java
- module-common/src/main/java/com/mile/resolver/reply/ReplyVariableResolver.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/comment/service/dto/CommentResponse.java
- module-domain/src/main/java/com/mile/commentreply/domain/CommentReply.java
- module-domain/src/main/java/com/mile/commentreply/repository/CommentReplyRepository.java
- module-domain/src/main/java/com/mile/commentreply/service/CommentReplyService.java
- module-domain/src/main/java/com/mile/commentreply/service/dto/ReplyCreateRequest.java
- module-domain/src/main/java/com/mile/commentreply/service/dto/ReplyResponse.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- Closes #296 
1. PathVariableResolver 구현해서 WebConfig에 등록해줬습니다 : 이 부분 등록 안해줘서 30분 동안 헤매였네요..
2. CommentReply 엔티티를 따로 만들어 대댓글을 등록할 테이블을 구성했습니다.
3. 대댓글 삭제 및 대댓글 등록 구현했습니다.
4. 게시글이나 댓글 삭제 시 관련 데이터 삭제를 위해 모두 삭제되는 로직을 추가했습니다.
- 대댓글 관련 API를 모두 구현해서 코드가 다소 많습니다 ㅠ.ㅠ
> #296 [feat] 대댓글 관련 기능 전체 구현

- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- Closes #283
1. 내용
기존 로직에서 비공개 모임에 대한 조회 로직을 반영하지 않고 있어서, 해당 부분을 추가했습니다.
베스트 모임 조회에서 최신 1주일 기준 가장 많은 글이 생성된 비공개 모임의 top 3를 반환했습니다.
```java
@Query("SELECT m FROM Post p JOIN p.topic t JOIN t.moim m WHERE m.isPublic = true AND p.createdAt BETWEEN :startOfWeek AND :endOfWeek GROUP BY m ORDER BY COUNT(p) DESC")
List<Moim> findTop3PrivateMoimsWithMostPostsLastWeek(Pageable pageable, @Param("startOfWeek") LocalDateTime startOfWeek, @Param("endOfWeek") LocalDateTime endOfWeek);
```
> #283 [refactor] 비공개 모임에 대한 조회 로직 수정

- module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/curious/domain/Curious.java
- module-domain/src/main/java/com/mile/curious/repository/CuriousRepository.java
- module-domain/src/main/java/com/mile/curious/service/CuriousService.java
- module-domain/src/main/java/com/mile/post/repository/PostRepository.java
- module-domain/src/main/java/com/mile/post/service/PostDeleteService.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameDeleteService.java
- Closes #284
멤버 삭제 API 에서 아래 로직을 보완했습니다.
1) 멤버가 작성한 글 삭제 -> 해당 글의 연관 데이터 삭제 (궁금해요, 댓글 등)
2) 멤버가 다른 글에 작성한 댓글 삭제
3) 멤버가 다른 글에 누른 궁금해요 삭제 
-> 이 경우, 해당 글의 작가의 '총 궁금해요 수' 감소 로직과 해당 글의 '총 궁금해요 수' 감소 로직도 함께 구현했습니다.
> #284 [refactor] 멤버 삭제 리팩토링

- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- Closes #322
1. 로직 변경
기존 베스트 모임 반환 로직은
최근 1주일 간 가장 많은 글을 올린 top 3의 public 모임과 해당 모임의 글을 반환하는 것이었습니다.
이 경우, 최근 1주일간 글이 올라오지 않았을 때에는 모임이 아예 반환되지 않은 경우도 있었고, 3개 미달인 (1-2개) 경우도 있었습니다.
그래서 기획 요구사항에 따라,
최근 1주일 간 가장 많은 글을 올린 top 3의 public 모임과 해당 모임의 글을 반환하되, 
3개가 미달인 경우, 해당 부족분만큼 "최신 글이 올라온 모임을 반환"하도록 했습니다.
1. Trouble Shooting
최신 글이 올라온 모임을 반환할 때, top 3에 해당하는 모임과 겹치면 안되기 때문에 exlcudeMoims를 전달하여 해당 모임을 제외한 모임을 반환하도록
moimRepository.findLatestMoimsWithExclusion(pageRequest, excludeMoims); 을 하였습니다.
이 때 쿼리는 아래와 같이 작성했는데요
```java
@Query("SELECT m FROM Post p JOIN p.topic t JOIN t.moim m WHERE m.isPublic = true AND m NOT IN :excludeMoims GROUP BY m ORDER BY MAX(p.createdAt) DESC")
```
그러나, 의도한 바와 다르게 쿼리 로그에 and 1=0 조건이 나타나서 빈 배열이 반환됐습니다. 알고 보니 이 문제는 findLatestMoimsWithExclusion 메소드에서 excludeMoims가 빈 …
> #322 [feat] 베스트 모임 반환 로직 구현

- module-domain/src/main/java/com/mile/curious/service/CuriousService.java
- Closes #326 
1. 동시성 이슈 관련 해결했습니다 (아직 발생한 적은 있지만 충분히 발생할 수 있다고 생각해서! )
- 현재는 post id 와 writer name id 가 각각 하나의 curious 테이블만 생성할 수 있다는 것을 보장해주는 데이터베이스 제약조건이 없었습니다. 이를 추가하고 만일 동시성(이중 체크임에도 불구하고 발생할 수 있는) 이슈가 발생했을 때, 해결하기 위한 코드를 구현했습니다.
-
> #326 [feat] 동시성 이슈 관련 해결

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
- module-api/src/main/java/com/mile/controller/writername/WriterNameControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/writername/domain/WriterName.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- module-domain/src/main/java/com/mile/writername/service/dto/WriterNameDescriptionResponse.java
- module-domain/src/main/java/com/mile/writername/service/dto/WriterNameDescriptionUpdateRequest.java
- module-domain/src/main/java/com/mile/writername/service/dto/WriterNameShortResponse.java
- Closes #333 
1. WriterName에서 짧은 내용만 Get 하는 Response -> module-domain/src/main/java/com/mile/writername/service/dto/WriterNameShortResponse.java
2. WriterName Description도 함께 Get하는 Response -> module-domain/src/main/java/com/mile/writername/service/dto/WriterNameDescriptionResponse.java
3. 소개글 수정을 위한 Patch API 구현
- 놓친 부분을 뒤늦게 확인하고 빠르게 구현하느라 전달을 못했습니다!.. 그리고 3가지 API를 함께하느라 PR이 다소 큽니다..! 양해 부탁드려요!
저희가 이 플로우를 놓쳤더라구요!
이 세개의 API를 구현했습니다!
> #333 [feat] 글모임 뷰 - 필명 수정을 위한 플로우 구현

- module-api/src/main/java/com/mile/controller/comment/CommentController.java
- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/post/PostController.java
- module-api/src/main/java/com/mile/controller/topic/TopicController.java
- module-api/src/main/java/com/mile/controller/user/UserController.java
- module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
- module-common/build.gradle
- module-common/src/main/java/com/mile/config/filter/PrincipalHandler.java
- module-common/src/main/java/com/mile/config/redis/RedisConfig.java
- module-common/src/main/java/com/mile/config/web/WebConfig.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/exception/model/TooManyRequestException.java
- module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
- module-common/src/main/java/com/mile/interceptor/DuplicatedInterceptor.java
- Closes #340
글 생성에 대한 동시성 이슈를 발견하고, 해결하기 위해 중복된 요청에 대한 에러 처리를 하였습니다.
DuplicatedInterceptor에서 UserId 기반으로 키를 생성합니다.
요청이 들어오면 이 키가 이미 존재하는지 확인하고,
없으면 저장하여 요청을 처리합니다.
만약 이미 존재하면, TooManyRequestException 예외를 발생합니다.
요청 완료 후 Redis에서 해당 키를 삭제하는 로직입니다!
> #340 [feat] 중복된 요청 에러 처리

- module-api/src/main/java/com/mile/controller/topic/TopicController.java
- module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
- module-common/src/main/java/com/mile/utils/SecureUrlUtil.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustomImpl.java
- module-domain/src/main/java/com/mile/post/service/PostGetService.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- module-domain/src/main/java/com/mile/topic/service/dto/PostListInTopicResponse.java
- Closes #341 
1. 무한 스크롤의 경우, 커서 기반 페이지네이션을 진행합니다.
기존 페이지네이션의 경우 offset 기반으로 지금 있는 페이지에 해당하는 값들을 보여줍니다. 무한 스크롤의 경우 받아온 데이터 이후의 값만 보내줘야하기 때문에 현재 커서가 어디있는지를 뜻하여 커서 기반 페이지네이션을 진행합니다.
2. 이를 위해서 받아와야 하는 값은 지금까지 받아온 값의 가장 최상의 ID입니다.
RequestParameter로 해당 값이 Null이 될 수 있도록 설정하였습니다.
3. 리턴값에 hasNext 필드를 추가하여 다음 페이지가 있는지 포함하여 만일 이 페이지가 마지막일 경우를 담았습니다.
-> 이는 우선 SQL문을 통해 7개를 뽑은 후, 7개가 된다면 PageSize보다 큰 것이기 때문에 다음 페이지가 있다는 것으로 판단하여 Boolean 값을 리턴했습니다.
-
> #341 [feat] 글감별 글 조회 무한 스크롤(페이지네이션) 구현

- module-api/src/test/java/com/mile/cocurrency/DuplicatedInterceptorTest.java
- Closes #344 
1. ExecutorService로 여러개의 스레드를 생성 후, 스레드에서 여러번의 요청을 보내는 테스트 코드를 작성하였습니다!
2. 그 때 token을 같이 보내는 과정을 Authentication 객체를 만들어 이를 담아 보내는 방식으로 대체했습니다!
3. 4번의 요청에서 OK는 1번 나머지는 예외를 던져야하기 때문에 이를 검증하는 테스트 코드를 작성했습니다!
-
> #344 [feat] Too Many Request 테스트 코드 작성

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/MoimPublicStatusResponse.java
- Closes #361
1. 내용
- 글모임 공개여부 조회 api를 구현하였습니다.
> #361 [feat] 공개여부 조회 구현

- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/commentreply/service/CommentReplyService.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- Closes #377 
1. 대댓글 숫자가 반영이 안되고 있었음을 깨닫고 반영하는 로직을 구현했습니다!
2. iterator를 통해 comment별로 reply의 개수를 더해주었습니다!
3. 로직이 비정규화를 반영하면 어떨까라는 생각이 드네요..!
-
> #377 [feat] 대댓글 count 반영

- module-domain/src/main/java/com/mile/comment/service/CommentGetService.java
- module-domain/src/main/java/com/mile/commentreply/repository/CommentReplyRepository.java
- module-domain/src/main/java/com/mile/commentreply/service/CommentReplyGetService.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- module-domain/src/main/java/com/mile/writername/service/dto/WriterNameInfoResponse.java
- Closes #381 
1. 관리자 페이지 멤버 모임장 여부 추가하였습니다.
2. 댓글 개수에서 대댓글 개수도 포함할 수 있게 변경하였습니다.
-
> #381 [feat] 관리자 페이지 멤버관련 수정

- module-domain/src/main/java/com/mile/moim/domain/Moim.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/writername/domain/WriterName.java
- module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- Closes #386
글모임과 필명 모두 "normalizedName"로 띄어쓰기를 제거하고, 대소문자를 소문자로 변경한 필드를 두었습니다.
글모임명, 필명 생성 과정에서 normalizedName 값을 저장하도록 하였고,
(현재 수정 로직이 있는 경우에 대해서는) normalizedName 값도 수정되도록 하였습니다.
현재 로직에서는 이렇게 normalizedName이 name과 함께 생성 및 변동될 수 있도록 하였지만 
데이터 무결성을 확실히 지킬 수 있는 방법을 찾아보았고 prepersist, preupdate 어노테이션을 적용해보았습니다.
엔티티가 db에 저장되기 전, 그리고 엔티티의 상태가 변경되어 데이터베이스에 업데이트되기 전에 호출되는 어노테이션입니다.
> #386 [feat] 필명, 글모임명 중복체크 중 띄어쓰기 관련 로직 구현

- module-domain/src/main/java/com/mile/post/service/PostCreateService.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/topic/service/TopicCreator.java
- module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
- module-domain/src/main/java/com/mile/topic/service/TopicRetriever.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- module-domain/src/main/java/com/mile/topic/service/TopicUpdator.java
- module-domain/src/main/java/com/mile/topic/service/dto/TopicUpdator.java
- Closes #395 
TopicService를 TopicRetriever, TopicUpdator, TopicRemover, TopicCreator 로 분리 하여 리팩토링하였습니다!!
topicService의 findById 를 topicRetriever로 이동하였는데요, 아래와 같은 고민이 있습니다!
기존에 다른 서비스에서 (postService 등) 에서 topicService의 findById를 호출하고 있었는데요, 이 경우 아래 두가지 방안 중 고민이 됩니다
1.  TopicService에서 TopicRetriever의 findById 호출
즉, topicService에 findById 메서드를 유지하되, topicRetriever의 findById 메서드를 호출한다. -> 이 경우, 다른 서비스에서 findById를 호출할 경우, topicService를 통해 호출한다.
2. TopicRetriever의 findById만 유지
즉, topicService에서 findById 메서드를 삭제하고, topicRetriever의 findById 메서드만 유지한다. -> 이 경우, 다른 서비스에서 findById 를 호출할 경우, topicRetriever를 통해 호출한다.
1번의 장점은 다른 서비스가 모두 topicService를 통해 가도록 단일 진입점을 유지할 수 있고,
topicRetriever를 변경할일이 생겨도 다른 서비스들에 영향을 미치지 않을수 있다.. 는 장점이 있는데요
그리고 순환참조 문제를 완벽히 방지하려면 1번 안이 더 맞지 않나 라는 생각이 드네요
중간 레이어가 하나 있다는 …
> #395 [refactor] Topic 관련 리팩토링

- module-api/src/test/java/com/mile/cocurrency/DuplicatedInterceptorTest.java
- module-api/src/test/java/com/mile/cocurrency/UniqueNameLockTest.java
- module-api/src/test/java/com/mile/controller/MoimControllerTest.java
- module-domain/src/main/java/com/mile/moim/service/dto/TopicCreateRequest.java
- Closes #424 
1. 글모임 컨트롤러에 대한 인수(단위)테스트를 작성하였습니다.
테스트 메서드 중 a, b ,z 가 되어있는 메서드가 있는데, 이는 먼저 혹은 나중에 실행되어야 하는 메서드로 순서를 지정해주기 위해 이와 같이 진행했습니다.
2. 테스트를 작성하다가 request에 있는 글자수 제한 문제를 발견해서 수정했습니다.
3. 기존에 있던 security를 제거했기 때문에 기존 테스트 코드에서 인증 방식을 수정했습니다.
-
> #424 [test] 글모임 도메인 컨트롤러 단위테스트 코드 작성

- module-domain/src/main/java/com/mile/user/service/UserService.java
- module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java
- Closes #426 
1. 기존 findAll 후 moim을 받아오는 작업에서 발생하던 N+1문제를 fetch Join을 사용하므로써 해결하였습니다. 
--- 해결 전 (최대 6번의 쿼리 진행(유저를 찾아오는 질의 + 모임 개수 마다 select moim 하는 질의)
--- 해결 후 (최대 1번의 쿼리 진행 -> fetch join으로 모든 moim 값 받아옴)
-
> #426 [refactor] 사용자 글모임 list 조회 N+1 해결

- module-api/src/main/java/com/mile/common/utils/ContextHolderUtil.java
- Closes #436 
1. Context Util에서 검증 과정 없이 JWT 토큰에서 바로 유저를 가져와서 에러가 발생했습니다. 그래서 Context Util에 검증 로직을 추가하였습니다!
-
> #436 [feat] Context Util에 토큰 검증 로직 추가

- module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
- module-domain/src/main/java/com/mile/commentreply/repository/CommentReplyRepository.java
- module-domain/src/main/java/com/mile/post/repository/PostRepository.java
> #443 [feat] clearAutomatically 추가

- module-api/src/main/java/com/mile/common/utils/ContextHolderUtil.java
- module-api/src/main/java/com/mile/controller/comment/CommentController.java
- module-api/src/main/java/com/mile/controller/comment/CommentControllerSwagger.java
- module-api/src/main/java/com/mile/controller/user/UserController.java
- module-api/src/main/java/com/mile/controller/user/facade/AuthFacade.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
- module-domain/src/main/java/com/mile/comment/domain/Comment.java
- module-domain/src/main/java/com/mile/comment/service/CommentRetriever.java
- module-domain/src/main/java/com/mile/comment/service/CommentService.java
- module-domain/src/main/java/com/mile/commentreply/domain/CommentReply.java
- module-domain/src/main/java/com/mile/commentreply/service/CommentReplyRetriever.java
- module-domain/src/main/java/com/mile/commentreply/service/CommentReplyService.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimRetriever.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/post/service/PostRetriever.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/post/service/dto/PostCreateRequest.java
- module-domain/src/main/java/com/mile/writername/domain/WriterName.java
- Closes #447 
(중요도 상)
1. 에러 코드 세분화 -> 글 상세 뷰에서 발생하는 예외 케이스들의 코드를 세분화 하였습니다.
2. 글 모임 뷰에서 글쓴이가 모두 글쓴이로 보이지 않던 현상을 해결했습니다. equals를 오버라이드 해서 재정의하면서 해결했습니다. 
- 제가 파악하기에는, 같은 영속성 컨텍스트에 존재하지 않는 이유로 equals가 제대로 작동하지 않은 것 같습니다 [링크](https://impati.github.io/posts/jpa-equals/)
3. 글 상세 뷰에서 방장에 대해 글 삭제, 댓글 대댓글 삭제 권한이 존재한다는 점을 발견하였습니다. 그래서 이 요구사항에 적합하게 수정하였습니다.
---
(중요도 하)
4. 이전에 반영되어 있지 않던, 댓글 대댓글 길이 관련한 DB 제약사항 변경했습니다.
5. WriterName테이블의 Constraints와 이름 명명이 카멜케이스가 아닌 다른 방법으로 적용되어 있어서 수정했습니다.
- 변경사항이 큽니다! 이번 주까지 반영해야하니 리뷰 부탁드려요!
> #447 [feat] 글 상세 뷰 에러 코드 세분화

- module-api/src/test/java/com/mile/controller/MoimControllerTest.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/topic/repository/TopicRepository.java
- module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
- module-domain/src/main/java/com/mile/topic/service/TopicService.java
- Closes #452 
1. 관리자 페이지 멤버 관리 에러 코드 세분화하였습니다!
2. 관리자 페이지에서 글모임 정보 수정 시, 만약 글모임 이름 변경이 있을 시에만 validate문을 통과하게 진행했습니다.
3. 기존에 글모임 삭제 프로세스에서 batch query를 사용했는데, 이 때 `@Transactional`을 처리해주기 위해 (처리해주지 않아 에러가 발생했었습니다) 레포지토리 메서드에 붙였습니다.
-
> #452 [feat] 관리자 페이지 멤버 관리 에러 코드 세분화

- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- Closes #459
1. 내용
- 글모임 생성뷰 에러코드 세분화를 진행했습니다!
- 관리자페이지 글모임정보 뷰에 대해서는 추가적으로 세분화할 내용이 없습니다!
> #459 [feat] 글모임 생성 뷰 에러코드 세분화

- module-api/src/main/java/com/mile/config/WebConfig.java
- Closes #469 
1. CORS 허용 범위 수정
-
> #469 [feat] CORS 허용 범위 수정

- module-api/src/main/java/com/mile/controller/user/UserController.java
- module-api/src/main/java/com/mile/controller/user/UserControllerSwagger.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- Closes #471 
1. 기존 Refresh Token이 http only 속성 때문에 js에서 parameter로 전달하는 것이 불가능해서 Cookie를 사용하기로 했습니다!
2. 대신 Cookie의 만료시간을 늘렸습니다!
-
> #471 [feat] Refresh Token 이용 방식 수정

- module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
- Closes #464 
1. 내용
필명 리스트를 writername id 기준 오름차순 정렬로 변경했습니다. 
글모임장이 제일 먼저 오도록 쿼리문을 수정하였습니다.
> #464 [feat] 필명 리스트 오름차순 정렬

- module-domain/src/main/java/com/mile/moim/service/MoimRetriever.java
- Closes #486
1. 내용
베스트모임 리턴 에러가 PageRequest 개수를 잘못 입력하여 발생한 에러여서, 수를 변경했습니다 !
-
> #486 [fix] 베스트모임 페이지 개수 변경

- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimRetriever.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
- Closes #501 
1. best 글모임을 받아올 때 빈 글모임이 오는 것을 확인하였습니다!
- 임시 저장글에 대해서도 counting을 하고 있었기 때문이라는 점을 발견했습니다. 그래서 이에 대해 수정을 진행했습니다
- 그리고 Pageable을 넘기면 limit 3 이 필요 없어서 이를 지워주었습니다!
-
> #501 [fix] best 글모임 받아올 때 임시저장 글 제외

- module-api/src/main/java/com/mile/common/resolver/comment/CommentVariableResolver.java
- module-api/src/main/java/com/mile/common/resolver/moim/MoimVariableResolver.java
- module-api/src/main/java/com/mile/common/resolver/post/PostVariableResolver.java
- module-api/src/main/java/com/mile/common/resolver/reply/ReplyVariableResolver.java
- module-api/src/main/java/com/mile/common/resolver/topic/TopicVariableResolver.java
- module-api/src/test/java/com/mile/controller/MoimControllerTest.java
- module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
- module-domain/src/main/java/com/mile/commentreply/service/CommentReplyRetriever.java
- module-domain/src/main/java/com/mile/common/utils/SecureUrlUtil.java
- module-domain/src/main/java/com/mile/topic/service/TopicRetriever.java
- module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java
- Closes #511 
변경된 에러코드 아카이빙용으로 적어놓겠습니다!
- 글감이 존재하지 않을 때 발생했던 에러 40408, 40409, 40413 -> 40408로 통일
- 댓글이 존재하지 않을 때, 대댓글이 존재하지 않을 때 발생하는 에러코드 40406으로 통일
- 필명이 존재하지 않을 때 -> 유저가 존재하지 않는 것으로 에러코드 통일 40400
- PathVariable (요청 URI가 존재하지 않을 때) 40014, 40010 -> 40413으로 통일
-
> #511 [feat] 에러코드 요청에 따른 수정

- .gitattributes
- module-domain/src/main/java/com/mile/common/config/CacheConfig.java
- module-domain/src/main/java/com/mile/moim/repository/MoimPopularInfoRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/lock/AtomicValidateMoimPopulerInfo.java
- module-domain/src/main/java/com/mile/moim/service/lock/MoimPopularInfoAspect.java
- module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoRegister.java
- module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoService.java
- module-external/src/main/java/com/mile/aws/utils/S3Service.java
- Closes #538 
1. 만약 인기 작가/ 글 을 연산하였을 때 null 값이면 cache에 그대로 null을 저장해 null 이 리턴되는 문제가 있었습니다. cache에 null 값이 저장되지 않게 수정하였습니다 (논의 후 결정)
2. 그리고 인기 작가/글이 조회 때문에 발생하여 동시성 문제를 해결하기 위해 AOP 기반의 분산락을 구현했습니다.
3. 분산락을 구현하던 도중 내부 호출 함수에 어노테이션을 걸어놓으니, 분산락이 작동하지 않아서 (프록시 객체로 사용해야하는데) 클래스를 분리했습니다.
-
> #538 [feat] 모임당 인기글/ 인기 작가 로직 수정

- module-api/src/main/java/com/mile/controller/moim/MoimController.java
- module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoRegister.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
- module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustomImpl.java
- module-domain/src/main/java/com/mile/post/service/PostRemover.java
- module-domain/src/main/java/com/mile/post/service/PostRetriever.java
- module-domain/src/main/java/com/mile/writername/domain/MoimRole.java
- Closes #522 
1. Moim Controller 내부 인가체제 모두 변경했습니다! userId를 넘겨야하는경우는 진행하지 않았습니다!
-
> #522 [feat] MoimController 인가체제 변경

- module-domain/src/main/java/com/mile/moim/domain/popular/MoimPopularInfo.java
- module-domain/src/main/java/com/mile/moim/repository/MoimPopularInfoRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/moim/service/dto/response/MoimMostCuriousWriterResponse.java
- module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoRegister.java
- Closes #551 
1. MoimPopularInfo 내부에 있는 Collection을 List가 아닌 Set으로 설정하여 Fetch Join시 Multiple Bag Exception이 나지 않게 수정하였습니다!
2. 캐시를 수정하려고 했으나 지금 수정하지 않아도 될 것 같아 안하였습니다!
-
> #551 [feat] MoimPopularInfo 자료구조 Set으로 변경 및 n+1 문제 해결

- module-domain/src/main/java/com/mile/moim/domain/popular/MoimPopularInfo.java
- module-domain/src/main/java/com/mile/moim/service/dto/request/MoimInfoModifyRequest.java
> #565 [feat] 글모임 정보 수정 API validation 수정

- module-domain/src/main/java/com/mile/common/log/P6spySqlFormat.java
- module-domain/src/main/java/com/mile/common/log/P6spySqlFormatConfig.java
- module-domain/src/main/java/com/mile/common/log/SqlFunctionLoggingModule.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- Closes #564 
1. p6spy로 sql 문의 인자 포함된 로깅을 제공하고, 이를 포맷한 후 진입점을 로깅할 수 있게 AOP 방식으로 repository 내부 메서드 호출 시 MDC에 진입점을 담도록 진행했습니다. 그리고 이를 logging formatter에서 꺼내오도록했습니다.
2. 이 때 MDC.get 값은 경우는 null 인 경우를 보장해주어서 NPE 나는 경우를 걱정하지 않아도 될 것이라고 판단했습니다.
결과는 아래와 같습니다!
-
> #564 [feat] sql 로깅 모듈 구현

- module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
- module-api/src/main/java/com/mile/controller/user/facade/AuthFacade.java
- Closes #580 
- 
1. Refresh Token이 만료되면 500에러가 발생하여서 수정하고, 머지하면서 prod yml 수정하겠습니다!
-
> #580 [feat] 리프레시 토큰 만료시 500 에러 아닌 에러 타도록 수정

- module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoRegister.java
- module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoService.java
- Closes #581 
1. 글모임 인기 정보 관련 set이 들어갈 때, register를 접근해서 하는 것이 아닌, register 밖에서 lock을 획득하려고 한 뒤에 획득하면 접근하도록 변경했습니다. (캐시의 동시성을 보장하기 위해)
2. 분산락 키가 공통이어서 , 모든 요청에 대해 모임 구분 없이 락을 걸고 있었는데, 모임별로 분산락을 걸도록 수정했습니다.
-
> #581 [feat] 글모임 정보 받아올 시 분산락 위치 변경

- module-api/src/main/java/com/mile/controller/external/InternalController.java
- module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
- module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
- module-domain/src/main/java/com/mile/moim/service/MoimRetriever.java
- module-domain/src/main/java/com/mile/moim/service/MoimService.java
- module-domain/src/main/java/com/mile/post/repository/PostRepository.java
- module-domain/src/main/java/com/mile/post/service/PostRetriever.java
- module-domain/src/main/java/com/mile/post/service/PostService.java
- module-domain/src/main/java/com/mile/post/service/dto/response/PostDataResponse.java
- Closes #592 
1. 글/ 글모임 메타데이터용 get 구현
-성능이슈가 살짝 우려되지만, 배포할 때 한 번 사용되는 API라 넘어갈 예정
> #592 [feat] 글/ 글모임 메타데이터용 get 구현
