build.gradle
module-api/build.gradle
module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-api/src/main/java/com/mile/controller/user/UserControllerSwagger.java
module-api/src/test/java/com/mile/ApiApplicationTests.java
module-common/src/main/java/com/mile/config/security/SecurityConfig.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-common/src/main/java/com/mile/exception/model/ForbiddenException.java
module-common/src/main/java/com/mile/filter/JwtAuthenticationFilter.java
module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
module-domain/src/main/java/com/mile/config/BaseTimeEntity.java
module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
module-domain/src/main/java/com/mile/moim/serivce/MoimService.java
module-domain/src/main/java/com/mile/moim/serivce/dto/ContentListResponse.java
module-domain/src/main/java/com/mile/penNameProfile/serivce/PenNameProfileService.java
module-domain/src/main/java/com/mile/post/Post.java
module-domain/src/main/java/com/mile/topic/domain/Topic.java
module-domain/src/main/java/com/mile/topic/repository/TopicRepository.java
module-domain/src/main/java/com/mile/topic/serivce/TopicService.java
module-domain/src/main/java/com/mile/topic/serivce/dto/ContentResponse.java
module-domain/src/main/java/com/mile/writerName/domain/WriterName.java
module-domain/src/main/java/com/mile/writerName/repository/WriterNameRepository.java
module-domain/src/main/java/com/mile/writerName/serivce/WriterNameService.java

- Closes #18 
1. 작업할 때 편하게 테스트 하기 위해 SecurityConfig WHITE_LIST에 `/api/**`를 넣어서 요청 허용해주었습니다 : `/api` 로 시작하는 모든 요청 토큰 없어도 접근 가능하다는 뜻
2. 스웨거 작업해주었습니다.
3. 토큰 관련 예외 처리 해주었습니다! -> Bearer로 시작하지 않을 경우 BadRequestException 발생 설정
4. 글감 도메인 변경 사항 엔티티에 반영했습니다!
- 커밋 개수가 커보이는데 그렇게 크지 않아서 All file change에서 봐주시면 됩니다! 커밋 메시지 변경하느라 stash 해버렸네요 😅 주의하겠습니다!

#18 [feat] GET - 에디터 뷰 글감 조회  

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-common/src/main/java/com/mile/exception/model/ConflictException.java
module-domain/src/main/java/com/mile/curious/domain/Curious.java
module-domain/src/main/java/com/mile/curious/repository/CuriousRepository.java
module-domain/src/main/java/com/mile/curious/serivce/CuriousService.java
module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #27 
궁금해요 삭제 API를 구현하였습니다.
궁금해요를 이미 삭제했는데, 또 삭제한 경우 혹은 궁금해요를 생성하지 않았는데 삭제를 요청한 경우에 대한 예외처리를 구현했습니다.

#27 궁금해요 삭제 API 구현

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/curious/serivce/CuriousService.java
module-domain/src/main/java/com/mile/curious/serivce/dto/CuriousInfoResponse.java
module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #34 
궁금해요 개수 및 궁금해요 여부 조회를 구현하였습니다!
기존에 구현된 메소드를 활용해 구현했습니다.

#34 궁금해요 개수 및 궁금해요 여부 조회 API 구현

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/repository/PostRepository.java
module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/WriterAuthenticateResponse.java

- Closes #31 
1. 스웨거 작성하였습니다!
2. Post 도메인에 Writer 연관관계가 없어 추가하였습니다!
- 코드 수정할 내용 있으면 알려주시면 감사하겠습니다 :>

#31 [feat] 글 삭제/수정 권한 여부 API 구현

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostPutRequest.java
module-domain/src/main/java/com/mile/topic/serivce/TopicService.java

- Closes #38 
1. 스웨거 작성 완료했습니다!
2. Post 엔티티에 updatePost 메서드 추가했습니다! 글 저장 메서드 사용할 때 사용하시면 좋을 것 같습니다!
- 수정사항 알려주시면 감사하겠습니다 :>

#38 [feat] 글 수정 구현

---

Dockerfile

- Closes #52 
1. dockerfile 수정했습니다.
-

#52 [feat] dockerfile 수정

---

module-api/src/main/resources/logback-spring.xml

- Closes #58 
1. 로깅 파일 dev에서도 보이게 수정했습니다!
-

#58 [feat] 로깅 파일 수정

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-common/src/main/java/com/mile/utils/DateUtil.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostGetResponse.java

- Closes #66 
글 조회 API 를 구현하였습니다!
1. DateUtil 내 month 가 JANUARY 와 같이 불러와져서 일부 변경하였습니다!
2. 기존 API DOCS 에서는 WriterName의 image url 도 같이 보내주었는데, WriterName은 사진이 없다고 전달 받아서 DOCS와 DTO 를 변경하였습니다!

#66 [feat] GET - 글 조회 API 구현

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-domain/src/main/java/com/mile/post/service/dto/PostPutRequest.java

- Closes #47 
1. Dto에 swagger 예시와 validation 처리해주었습니다!
-

#47 [feat] 게시글 수정 validation

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/TemporaryPostGetResponse.java
module-domain/src/main/java/com/mile/post/service/dto/TemporaryPostTopicGetResponse.java

- Closes #71 
임시저장글을 조회하는 API 를 구현했습니다!
해당 postId의 글이 임시저장글이 아닌 경우에 대해 예외처리를 하였습니다.

#71 [feat] GET - 임시저장글 조회

---

module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java

- Closes #74 
1. 웹에서 발급한 redirect-uri로 변경했습니다!
-

#74 [feat] kakao redirect uri 변경

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimMostCuriousPostResponse.java
module-domain/src/main/java/com/mile/post/service/PostCuriousService.java

- Closes #77 
1. DTO에 Post ID 담도록 수정했습니다!
-

#77 [fix] DTO 수정

---

docker-compose.yml
module-auth/build.gradle

- Closes #76 
1. docker-compose.yml 작성
- docker compose에 redis 관련 설정 추가하고, redis 의존성 추가했습니다!
-

#76 [feat] docker-compose.yml 작성

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostCreateRequest.java

- Closes #80 
POST - 글 생성 API 를 구현하였습니다!
제목과 내용은 ""과 " "도 허용되지 않도록 NotBlank Validation 붙였습니다.

#80 POST - 글 생성 API 구현

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostPutRequest.java
module-domain/src/main/java/com/mile/writerName/service/dto/WriterNameResponse.java

- Closes #85 
1. createPost 문에서 WriterNameResponse return 하도록 변경해주었습니다!
2. 스웨거 작성 완료했습니다.
3. PutDto에서 NotNull 설정해주었습니다
-

#85 [feat] 임시 저장된 글 작성 PUT API

---

docker-compose.yml
module-auth/build.gradle

- Closes #95 
1. redis 모듈 제거
-

#95 [feat] redis 모듈 제거

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostCuriousResponse.java

- Closes #91 
유저가 궁금해요를 했는지 여부 반환하도록 수정하였습니다!

#91 [refactor] 유저가 궁금해요를 했는지 여부 반환하도록 수정

---

module-domain/src/main/java/com/mile/moim/domain/Moim.java
module-domain/src/main/java/com/mile/post/domain/Post.java

- Closes #113 
1. 이미지 없을 경우 기본 이미지 insert 처리
2. 글모임 소개 최대 길이 증가
-

#113 [feat] 이미지 없을 경우 기본 이미지 insert 처리

---

module-domain/src/main/java/com/mile/recommend/service/RecommendService.java

- Closes #115 
1.  글감 추천 스케쥴링 방식 변경했습니다! 
-

#115 [feat] 글감 추천 스케쥴링 방식 변경

---

module-domain/src/main/java/com/mile/moim/service/dto/MoimInfoResponse.java

#116 [fix] DTO 수정

---

module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimCuriousPostListResponse.java
module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/repository/PostRepositoryImpl.java
module-domain/src/main/java/com/mile/post/service/PostCuriousService.java
module-domain/src/main/java/com/mile/writerName/domain/WriterName.java
module-domain/src/main/java/com/mile/writerName/service/WriterNameService.java

- Closes #121 
1. 궁금해요 top2 게시글 관련 쿼리문 수정
2. 길이가 0일경우 not found 에러 반환하도록 구현
3. 리턴할 때 curiousCount 체크
4. 리턴 dto 길이 수정
-

#121 [fix] 궁금해요 Top 2 API 관련 수정

---

module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/post/service/PostCuriousService.java

- Closes #126
클라의 요청에 따라 궁금해요 TOP 2 작가, 글이 없는 경우에 대한 404 예외처리를 제거하고 빈 리스트 반환으로 변경하였습니다!

#126 [refactor] 궁금해요 TOP 2 작가, 글에 대한 예외처리를 빈 리스트 반환으로 변경

---

module-common/src/main/java/com/mile/resolver/comment/CommentVariableResolver.java

- Closes #136 
1. CommentIdResolver가 MoimPathVariable 클래스를 구현하고 있어서 문제였습니다 ><
- 코드 복붙의 폐해..><

#136 [hotfix] Url 디코딩 버그 해결

---

module-domain/src/main/java/com/mile/moim/service/dto/MoimMostCuriousPostResponse.java
module-domain/src/main/java/com/mile/post/service/PostCuriousService.java

- Closes #138 
모임 TOP 2 글 DTO 변경했습니다!
클라의 요청으로 기본이미지인지 아닌지에 대한 boolean값을 보내줍니다!

#138 [refactor] 모임 TOP 2 글 DTO 변경

---

module-api/src/main/java/com/mile/controller/comment/CommentControllerSwagger.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
module-domain/src/main/java/com/mile/post/service/dto/PostCreateRequest.java
module-domain/src/main/java/com/mile/post/service/dto/PostPutRequest.java
module-domain/src/main/java/com/mile/post/service/dto/TemporaryPostCreateRequest.java

#142 [chore] 스웨거 수정

---

module-domain/src/main/java/com/mile/topic/service/dto/TopicOfMoimResponse.java

- Closes #144 
1. 오타 수정 
- 미안해요.><

#144 [fix] 오타 수정

---

module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java

- Closes #148 
1. 이미지 여부 필드 추가
-

#148 [feat] 이미지 여부 필드 추가

---

module-domain/src/main/java/com/mile/comment/service/CommentService.java
module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #158 
1. 내용
권한버그 해결하였습니다

#158 [fix] 권한버그 해결

---

module-domain/src/main/java/com/mile/moim/service/dto/BestMoimPostResponse.java

- Closes #160 
이미지 포함여부 boolean 값을 추가했습니다!

#160 [refactor] 이미지 포함여부 boolean 값 추가

---

module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
module-common/src/main/java/com/mile/utils/SecureUrlUtil.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/user/service/UserService.java

- Closes #161 
1. url 디코딩 예외 처리
2. 잘못된 요청 예외 처리
3. Data Integrity 예외 처리
-

#161 [feat] 예외 처리 구현

---

module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #166 
1. id URL 변경 반영
-

#166 [fix] transactional 추가

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/ModifyPostGetResponse.java

- Closes #168 
GET - 글 수정 시 조회 API 구현하였습니다!

#168 [feat] GET - 글 수정 시 조회 API 구현

---

module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java

- Closes #170 
1. [feat] kakao 리다이렉트 uri 변경
-

#170 [feat] kakao 리다이렉트 uri 변경

---

module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java

#170 [feat] redirect uri 변경

---

module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java

#170 [feat] 리다이렉트 uri 재설정

---

module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java
module-domain/src/main/java/com/mile/post/service/dto/PostGetResponse.java

- Closes #174 
1. post가 Anonymous 인 경우 대한 반환값을 수정했습니다!
-

#174 [fix] 글 조회 버그 해결

---

module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-domain/src/main/java/com/mile/comment/service/CommentService.java

- Closes #176 
1. 댓글 없을 시 기존에 예외처리를 하고 있었는데, 빈 배열 반환하는 것으로 변경하였습니다!
-

#176 [refactor] 댓글 조회시 예외처리 변경

---

module-api/src/main/java/com/mile/controller/test/TestController.java
module-api/src/main/resources/discord-appender.xml
module-common/src/main/java/com/mile/aspect/LoggingAspect.java
module-common/src/main/java/com/mile/config/filter/FilterConfig.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/filter/CustomServletWrappingFilter.java
module-common/src/main/java/com/mile/filter/MDCFilter.java
module-common/src/main/java/com/mile/filter/wrapper/CachedBodyRequestWrapper.java
module-common/src/main/java/com/mile/filter/wrapper/CachedBodyServletInputStream.java
module-common/src/main/java/com/mile/log/discord/DiscordAppender.java
module-common/src/main/java/com/mile/log/discord/DiscordWebHook.java
module-common/src/main/java/com/mile/log/discord/exception/ErrorLogAppenderException.java
module-common/src/main/java/com/mile/log/discord/model/Author.java
module-common/src/main/java/com/mile/log/discord/model/EmbedObject.java
module-common/src/main/java/com/mile/log/discord/model/Field.java
module-common/src/main/java/com/mile/log/discord/model/Footer.java
module-common/src/main/java/com/mile/log/discord/model/Image.java
module-common/src/main/java/com/mile/log/discord/model/JsonObject.java
module-common/src/main/java/com/mile/log/discord/model/Thumbnail.java
module-common/src/main/java/com/mile/utils/logging/ApiCallUtil.java
module-common/src/main/java/com/mile/utils/logging/HttpRequestUtil.java
module-common/src/main/java/com/mile/utils/logging/MDCUtil.java
module-common/src/main/java/com/mile/utils/logging/StringUtil.java

- Closes #107 
1. 기존에 구현했던 방식인 로그백 방식과 다르게 Api로 Post하는 방식으로 변경했습니다! 
2. 포맷도 정해지게 구현했습니다! 
3. 테스트 성공해라!
-

#107 [feat] 디스코드 무한로깅 버그 해결

---

module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java

- Closes #180
1. 내용
writer name 로직 수정
-

#180 [fix] 권한 API 버그 해결

---

module-domain/src/main/java/com/mile/post/service/PostAuthenticateService.java

- Closes #182 
1.  글쓴이 권한 확인 관련 사이드 이펙트 해결
-

#182 [fix] 글쓴이 권한 확인 관련 사이드 이펙트 해결

---

module-auth/src/main/java/com/mile/external/client/dto/UserLoginRequest.java
module-auth/src/main/java/com/mile/external/client/kakao/KakaoSocialService.java

- Closes #179 
1.  redirect uri 파라미터화
-

#179 [feat] redirect uri 파라미터화

---

module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
module-common/src/main/java/com/mile/utils/SecureUrlUtil.java

- Closes #185 
1. JwtValidationException이 어쩌다 안잡히고 서버 내부 오류가 되는지 모르겠습니다..
2. 그 외의 예외는 잡았습니다! 
-

#185 [feat] HttpMethodNotSupportedException 예외 및 디코딩 IllegalArgumentException 체크

---

module-domain/src/main/java/com/mile/moim/service/dto/BestMoimPostResponse.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimMostCuriousPostResponse.java
module-domain/src/main/java/com/mile/post/service/PostGetService.java
module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java

- Closes #187 
1. dto 및 정렬 방식 변경
2. 
-

#187 [feat] dto 및 정렬 방식 변경

---

module-domain/src/main/java/com/mile/user/repository/UserRepository.java
module-domain/src/main/java/com/mile/user/service/UserService.java

- Closes #189 
1. try catch 문 에러 해결
-

#189 [fix] try catch 문 에러 해결

---

module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #191 
1. imageURL 비교
-

#191 [feat] imageURL 비교

---

module-domain/src/main/java/com/mile/topic/service/TopicService.java

- Closes #193 
1. 글감 정렬 순서 변경
-

#193 [fix] 정렬 순서 변경

---

module-auth/build.gradle

- Closes #125 
1. redis를 다시 연동해봅시다..
-

#125 [fix] redis 재설정

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/PopularWriterListResponse.java
module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #210
1. ResponseEntity를 추가하였습니다!
2. 컨트롤러와 서비스단에서 메서드명을 통일하도록 변경하였습니다
3. MoimService에서 반환하는 DTO인 PopularWriterListResponse 가 WriterName 패키지보다는 Moim 패키지에 속하는 것이 맞다고 생각해서 위치를 변경했습니다.
4. 쿼리개선
- 필명의 궁금해요 개수가 0인지 확인하는 작업을 서비스단에서 getWriterNamesHaveCuriousCount 메소드로 하고 있었는데, 찾아보니 GreaterThan 문법이 있어서 이를 활용하여 필터링하는 과정을 데이터베이스 레벨에서 처리하도록 하였습니다.

#210 [refactor] 궁금해요 TOP 2 작가 리팩토링

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-domain/src/main/java/com/mile/topic/service/TopicService.java

- Closes #213 
1. ResponseEntity 추가
2. 메소드 네이밍을 더 직관적으로 변경 하였습니다!
-

#213 [refactor] GET - 글모임별 글감 카테고리 리팩토링

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-domain/src/main/java/com/mile/curious/service/CuriousService.java
module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #215 
1. ResponseEntity를 추가하였습니다!
-

#215 [refactor] GET - 궁금해요 개수 및 여부 조회 리팩토링

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryCustom.java
module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryCustomImpl.java
module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryImpl.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/BestMoimListResponse.java
module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustomImpl.java

- Closes #217 
1. ResponseEntity를 추가하였습니다!
2. 중복되는 코드를 제거하고 미사용 import 제거하였습니다.
3. 메서드명을 변경하였습니다.
4. for문이 많이 사용되고있었는데 stream 을 활용하여 변경하였습니다.
-

#217 [refactor] GET - 베스트 활동 모임 및 글 조회 리팩토링

---

module-api/src/main/java/com/mile/controller/comment/CommentController.java
module-api/src/main/java/com/mile/controller/comment/CommentControllerSwagger.java

- Closes #223 
1. 댓글 삭제 API response entity 적용하였습니다.
-

#223 [refactor] ResponseEntity 적용

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostGetResponse.java

- Closes #219 
1. ResponseEntity 추가하였습니다
2. moim 정보 가져오는 코드를 PostService에서 PostGetResponse.of 으로 이동하였습니다. 
-

#219 [refactor] 글 조회 API 리팩토링

---

module-auth/src/main/java/com/mile/jwt/redis/config/RedisConfig.java

#235 [hotfix] redis config

---

module-auth/src/main/java/com/mile/jwt/redis/config/RedisConfig.java

#235 [hotfix] value 값 변경

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-domain/src/main/java/com/mile/comment/service/CommentService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #234 
1. writerName 버그 사용하고 있어서 해결하였습니다!
2. responseEntity 추가하였습니다!
-

#234 [refactor] 게시글 댓글 list get api 리팩토링

---

.github/workflows/DEV-CD.yml
.github/workflows/PROD-CD.yml

- Closes #241 
DEV-CD.yml파일을 생성하고, 기존의 PROD-CD.yml파일에서 배포 브랜치를 main으로 변경하였습니다!

#241 [chore] DEV-CD.yml 생성

---

.github/workflows/DEV-CD.yml
.github/workflows/PROD-CD.yml

#243 [chore] cd 이름 변경

---

module-common/src/main/java/com/mile/utils/logging/MDCUtil.java

- Closes #245 
1. 포폴 쓰다가.. 미사용 메서드가 있는 걸 발견했네요! 삭제했습니다 :>
-

#245 [refactor] MDCUtils 미사용 메서드 삭제

---

module-domain/src/main/java/com/mile/comment/service/CommentService.java
module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java
module-domain/src/main/java/com/mile/topic/service/TopicService.java

- Closes #249 
1. 조회수 증가 로직 작성
2. 댓글 수 조회 로직 작성
3. 도메인 수정
-

#249 [feat] 글감별 글 리스트 조회수, 댓글 수 조회

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/WriterMemberJoinRequest.java
module-domain/src/main/java/com/mile/user/service/UserService.java
module-domain/src/main/java/com/mile/writername/domain/WriterName.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #251 
1. 모임 가입 로직 작성
2. 엔드포인트 작성
3. 기존 자동 가입 로직 삭제
-

#251 [feat] 모임 가입 로직 및 API 작성

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/WriterNameConflictCheckResponse.java
module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #253 
1. 쿼리문 exists를 활용하여 작성하였습니다!
-

#253 [feat] 필명 중복 여부 확인 API 구현

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimInvitationInfoResponse.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #255 
1. 초대 링크 글모임 정보 조회 구현
-

#255 [feat] 초대 링크 글모임 정보 조회 구현

---

module-api/src/main/java/com/mile/controller/topic/TopicController.java
module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-common/src/main/java/com/mile/utils/DateUtil.java
module-domain/src/main/java/com/mile/topic/service/TopicService.java
module-domain/src/main/java/com/mile/topic/service/dto/TopicDetailResponse.java

- Closes #265 
1. 글감 상세보기 구현
-

#265 [feat] 글감 상세보기 구현

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/TopicCreateRequest.java
module-domain/src/main/java/com/mile/topic/domain/Topic.java
module-domain/src/main/java/com/mile/topic/service/TopicService.java

- Closes #263 
1. 도메인 로직 & 엔드포인트 작성
-

#263 [feat] 글감 등록 API 구현

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimInfoOwnerResponse.java

- Closes #266 
1. 엔드포인트, 서비스 로직 구현
-

#266 [feat] 관리자 페이지 모임 정보 GET API

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-api/src/main/java/com/mile/controller/topic/TopicController.java
module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/topic/domain/Topic.java
module-domain/src/main/java/com/mile/topic/service/TopicService.java
module-domain/src/main/java/com/mile/topic/service/dto/TopicPutRequest.java

- Closes #260
1. 글감 수정 기능을 구현했습니다!

#260 [feat] 글감 수정 기능 구현

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/domain/Moim.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/InvitationCodeGetResponse.java

- Closes #274
1. 내용
초대링크 조회 기능을 구현 하였습니다!

#274 [feat] 초대링크 조회 기능 구현

---

module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/post/service/PostDeleteService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #285 
1. 임시 저장 글 삭제 엔드포인트 및 로직 구현
-

#285 [feat] 임시 저장 글 삭제 API 구현

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java

- Closes #536
앤드포인트 및 Success Message 오타가 있어 수정하였습니다.

#294 [fix] 오타 수정

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/utils/DateUtil.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimInvitationInfoResponse.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #298 
1. 모임 링크 접속 시 추가 사항 구현
-

#298 [feat] 모임 링크 접속 시 추가 사항 구현

---

module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimAuthenticateResponse.java

#300 [feat] 사용자 권한 확인 API 추가 구현 완료 

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimListOfUserResponse.java
module-domain/src/main/java/com/mile/moim/service/dto/MoimOfUserResponse.java
module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #304
상단바에 사용될 글모임 리스트 조회 API를 구현하였습니다!

#304 [feat] 나의 글모임 리스트 조회 GET API 구현

---

module-domain/src/main/java/com/mile/config/BaseTimeEntity.java
module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #297 
1. 임시 저장 글을 최종으로 확정할 때 createdAt을 업데이트하는 방식으로 해결했습니다.
-

#297 [fix] createdAt 임시저장 관련 버그 해결

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-domain/src/main/java/com/mile/comment/service/dto/CommentResponse.java
module-domain/src/main/java/com/mile/commentreply/service/dto/ReplyResponse.java

- Closes #306 
1. 중복 확인 관련 길이 조정 및 익명 여부 조회
-

#306 [feat] 중복 확인 관련 길이 조정 및 익명 여부 조회

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java

- Closes #309 
1. 중복확인 API 관련 에러 처리
-

#309 [hotfix] 중복확인 API 관련 에러 처리

---

module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
module-domain/src/main/java/com/mile/comment/service/CommentService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/dto/PostGetResponse.java

- Closes #281
1. 내용
리턴 값에 조회수, 댓글수, 궁금해요수를 추가하였습니다.

#281 [refactor] 글 조회 변경사항 반영

---

module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

#312 [feat] 필명 / 모임 관련 에러 해결

---

module-domain/src/main/java/com/mile/moim/service/dto/MoimCreateRequest.java

- Closes #313
글감 생성에 불필요한 필수값을 제거하였습니다.

#313 [fix] 글감 생성 필수값 수정

---

module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustomImpl.java
module-domain/src/main/java/com/mile/post/service/PostDeleteService.java
module-domain/src/main/java/com/mile/post/service/PostGetService.java

#316 [hotfix] 임시 저장 글 여부 조회 에러 해결

---

module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #318 
1. 모임 가입 관련 에러 처리
a. 이미 가입한 모임일 경우
b. 가입한 모임이 5개를 초과했을 경우
-

#318 [feat] 모임 가입 관련 에러 처리

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/user/UserController.java
module-api/src/main/java/com/mile/controller/user/UserControllerSwagger.java
module-domain/src/main/java/com/mile/moim/service/MoimService.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/user/service/UserService.java

- Closes #320 
1. URL이 카멜케이스로 되어있는 것을 변경하였습니다! 
- 내 글모임 List의 URL을 변경하면서 유저의 글 모임 리스트를 받아오는데, MoimController가 책임을 담당하고 있는게 모호해서 user/moims로 바꾸었는데요! 이에 대해 어떻게 생각하시는지 궁금합니다 :)
- 바뀐 URL은 명세서에 표시해놓았습니다!

#320 [fix] 기본 썸네일 및 URL 변경

---

module-domain/src/main/java/com/mile/post/service/PostService.java

- Closes #328 
1. 궁금해요 테이블 수정 관련 오류 해결
- 버그해결이므로 바로 머지하겠습니다!

#328 [hotfix] 궁금해요 테이블 수정 관련 오류 해결

---

module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #330 
1. 필명 생성 관련 최대 수 제한 수정
- 너무 가벼운 내용이라 어푸없이 머지하겠습니다 -:

#330 [fix] 필명 생성 관련 최대 수 제한 수정

---

module-common/src/main/java/com/mile/config/web/WebConfig.java

#335 [hotfix] CORS 에러 수정

---

module-api/src/main/java/com/mile/controller/writername/WriterNameController.java

#355 [fix] 엔드포인트 변경

---

module-domain/src/main/java/com/mile/post/domain/Post.java
module-domain/src/main/java/com/mile/post/service/PostCreateService.java

#338 [chore] 이미지변경

---

module-api/src/main/java/com/mile/controller/comment/CommentController.java
module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/topic/TopicController.java
module-api/src/main/java/com/mile/controller/user/UserController.java
module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
module-common/build.gradle
module-common/src/main/java/com/mile/config/redis/RedisConfig.java
module-common/src/main/java/com/mile/config/web/WebConfig.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-common/src/main/java/com/mile/exception/model/TooManyRequestException.java
module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
module-common/src/main/java/com/mile/interceptor/DuplicatedInterceptor.java

- Closes #340 
1. 중복된 요청 예외처리
-

#340 [hotfix] 중복된 요청 예외처리

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-auth/src/main/java/com/mile/authentication/CustomJwtAuthenticationEntryPoint.java

- Closes #353 
1. 엔드포인트로 작동하는 Spring Security로 인한 오류라고 파악되어 엔드포인트를 변경하였습니다!
-

#353 [feat] 엔드포인트 동일로 발생하는 오류 해결

---

module-domain/src/main/java/com/mile/topic/service/TopicService.java

- Closes #356
1. 내용
글감 순서 최신순으로 변경했습니다 -!

#356 [feat] 글감 순서 변경

---

module-api/src/main/java/com/mile/controller/moim/MoimController.java
module-api/src/main/java/com/mile/controller/post/PostController.java
module-api/src/main/java/com/mile/controller/topic/TopicController.java
module-api/src/main/java/com/mile/controller/user/UserController.java
module-api/src/main/java/com/mile/controller/writername/WriterNameController.java

#362 [hotfix] validation 처리

---

module-domain/src/main/java/com/mile/comment/service/dto/CommentResponse.java

#365 [feat] 글쓴이 댓글 익명 여부 수정

---

module-domain/src/main/java/com/mile/commentreply/service/dto/ReplyResponse.java

- Closes #368 
1. 대댓글 익명 처리 수정
-

#368 [feat] 대댓글 익명 처리 수정

---

module-domain/src/main/java/com/mile/commentreply/service/dto/ReplyResponse.java

#368 [hotfix] 대댓글 익명 처리 

---

module-domain/src/main/java/com/mile/moim/domain/Moim.java

- Closes #376 
1. 모임에 이미지가 없길래 확인해봤더니 url값이 빈 값이었습니다! default url을 지정해주었습니다!
-

#376 [feat] 모임 생성 및 수정 default image url 변경

---

module-domain/src/main/java/com/mile/moim/service/dto/TopicCreateRequest.java
module-domain/src/main/java/com/mile/topic/service/dto/TopicPutRequest.java

- Closes #383
글감설명이 필수값이 아니므로, NotBlank를 제거했습니다

#383 [refactor] 글감설명 필수값 제거

---

module-domain/src/main/java/com/mile/post/service/dto/PostGetResponse.java

- Closes #389
글 상세페이지 리턴값 시간 추가

#389 [feat] 글 상세페이지 리턴값 시간 추가

---

module-common/src/main/java/com/mile/utils/DateUtil.java
module-domain/src/main/java/com/mile/post/service/dto/PostGetResponse.java

- Closes #391
1. 내용
글 상세 페이지 조회 시 리턴 형식을 위한 메서드를 추가하고, 리턴값을 변경했습니다

#391 [feat] dateutil 메서드 추가 및 변경

---

module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

#401 [fix] 예외 수정

---

module-api/src/main/java/com/mile/config/WebConfig.java

- Closes #536
1. 내용
2. OPTIONS 추가
-

#403 [feat] CORS 문제해결

---

module-api/src/main/java/com/mile/config/WebConfig.java

#406 [fix] credential 추가

---

module-api/src/main/java/com/mile/common/resolver/user/UserIdHeaderResolver.java
module-api/src/main/java/com/mile/config/WebConfig.java

#409 [feat] userIdResolver 추가

---

module-api/src/main/java/com/mile/common/resolver/user/UserIdHeaderResolver.java
module-external/src/main/java/com/mile/aws/utils/S3Service.java

#412 [fix] Presigned url 만료 시간 재설정

---

module-api/src/main/java/com/mile/common/interceptor/DuplicatedInterceptor.java
module-api/src/main/java/com/mile/common/utils/ContextHolderUtil.java

#412 [fix] duplicate interceptor 토큰 인증 제외

---

module-domain/src/main/java/com/mile/curious/service/CuriousCreator.java
module-domain/src/main/java/com/mile/curious/service/CuriousRemover.java
module-domain/src/main/java/com/mile/curious/service/CuriousRetriever.java
module-domain/src/main/java/com/mile/curious/service/CuriousService.java

- Closes #421
1. 내용
Curious 리팩토링을 진행하였습니다 !!

#421 [refactor] Curious 리팩토링

---

README.md

- Closes #430 
1. 기존에 리드미에 있던 Git 전략이나 이 외 컨벤션들을 지웠습니다. 
2. 사진도 제거했습니다.
3. 모듈 수정 사항 반영했습니다!
-

#430 [docs] 리드미 수정

---

module-domain/src/main/java/com/mile/user/service/UserService.java
module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java

#428 [feat] conflict 해결

---

module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java

- Closes #441
1. 내용
API 변경사항에 따라
Swagger API Summary 이름 변경하였습니다.

#441 [chore] Swagger API Summary 이름 변경

---

module-domain/src/main/java/com/mile/writername/service/WriterNameRemover.java

#443 [feat] 필명 관련 데이터 삭제 플로우 추가

---

module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
module-domain/src/main/java/com/mile/commentreply/repository/CommentReplyRepository.java
module-domain/src/main/java/com/mile/curious/repository/CuriousRepository.java
module-domain/src/main/java/com/mile/post/repository/PostRepository.java
module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java

#443 [feat] JPQL Query Transactional 적용

---

module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-domain/src/main/java/com/mile/post/service/PostRetriever.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/PostUpdator.java
module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java

- Closes #454 
1. 글 에디터 페이지 에러코드 세분화 진행했습니다.
2. 그리고 진행하면서 사용하지 않는 함수들 & 쿼리문이 두번 나가고 있던 비효율적인 로직 리팩토링 했습니다
-

#454 [feat] 글 작성 페이지 에러 코드 세분화

---

module-api/src/main/java/com/mile/controller/user/facade/AuthFacade.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-domain/src/main/java/com/mile/post/service/PostRetriever.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/post/service/PostUpdator.java
module-domain/src/main/java/com/mile/user/service/UserService.java
module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java

- Closes #456 
1. 로그인 화면 에러 코드 세분화 및 리팩토링 진행하였습니다.
- 변경사항 적습니다!

#456 [feat] 로그인 화면 에러 코드 세분화 및 리팩토링

---

.github/workflows/CI.yml
module-api/build.gradle
module-api/src/test/java/com/mile/cocurrency/DuplicatedInterceptorTest.java
module-api/src/test/java/com/mile/cocurrency/UniqueNameLockTest.java
module-api/src/test/java/com/mile/controller/MoimControllerTest.java
module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
module-domain/src/main/java/com/mile/comment/service/CommentRetriever.java
module-domain/src/main/java/com/mile/commentreply/domain/CommentReply.java
module-domain/src/main/java/com/mile/commentreply/repository/CommentReplyRepository.java
module-domain/src/main/java/com/mile/commentreply/service/CommentReplyRetriever.java
module-domain/src/main/java/com/mile/config/querydsl/QueryDslConfig.java
module-domain/src/main/java/com/mile/moim/domain/Moim.java
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

- Closes #461 
1. CI.yml 에 Market Place Mysql 사용해서 테스트 환경 구축했습니다. [링크](https://github.com/marketplace/actions/setup-mysql)
2. 테스트 코드 User 한 명 상태에 국한되어 있던 부분을 User를 직접 생성해서 테스트하므로써 DB 환경과 의존성을 두지 않게 했습니다.
-

#461 [test] CI 테스트 환경 구축

---

module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java

- Closes #467 
1. 토큰 관련 수정 사항 반영
- 토큰 만료시간 적게 설정
- 토큰 검증 에러 코드 변경
-

#467 [feat] 토큰 관련 수정 사항 반영

---

module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
module-domain/src/main/java/com/mile/post/domain/Post.java

- Closes #466 
1. QA 사항 수정 하였습니다 -> 수정한 글에 대해서 사진 포함으로 변경되었을 때 containPhoto 값이 변하지 않는 부분 수정 하였습니다.
2. 웹 측에서 accessToken 만료시간 관련 요청이 들어와서 반영하였습니다
-

#466 [fix] 글 수정 시 사진 포함 여부 변경 update

---

module-api/src/main/java/com/mile/config/WebConfig.java

#475 [fix] webConfig origin 추가

---

module-api/src/main/java/com/mile/controller/user/UserController.java
module-api/src/main/java/com/mile/controller/user/UserControllerSwagger.java
module-api/src/main/java/com/mile/controller/user/facade/AuthFacade.java

- Closes #477 
1.  리프레시 로직 토큰 추출 X
-

#477 [feat] 리프레시 로직 토큰 추출 X

---

module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
module-api/src/main/java/com/mile/controller/user/UserController.java

- Closes #477 
1.  액세스 토큰 만료 시간 연장 및 cookie 속성 변경
-

#477 [feat] 액세스 토큰 만료 시간 연장 및 cookie 속성 변경

---

module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
module-domain/src/main/java/com/mile/comment/service/CommentService.java
module-domain/src/main/java/com/mile/post/service/PostRetriever.java
module-domain/src/main/java/com/mile/post/service/PostService.java
module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java

- Closes #482 
1. 40300 중 예외 분기가 안될 부분을 40306으로 분기했습니다!
2. 그리고 Bearer null 인경우도 로그인 안한 경우로 처리했습니다!
-

#482 [fix] 리스폰스 에러 코드 분기처리

---

module-domain/src/main/java/com/mile/moim/service/dto/WriterMemberJoinRequest.java
module-domain/src/main/java/com/mile/post/service/dto/PostPutRequest.java

- Closes #491 
1. dto validation 수정
- 필명 소개글 공백 가능
- 글 수정 API 10000자
-

#491 [hotfix] dto validation 수정

---

module-domain/src/main/java/com/mile/writername/service/dto/WriterNameDescriptionUpdateRequest.java

- Closes #493 
1. remove dto blank validation
-

#493 [feat] remove dto blank validation

---

module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java

- Closes #496 
1. add dto unnamed function

#496 [fix] add dto unnamed function

---

module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java

#496 [fix] QA 사항 반영

---

module-domain/src/main/java/com/mile/comment/service/CommentService.java
module-domain/src/main/java/com/mile/commentreply/service/CommentReplyService.java

- Closes #506 
1. if 문 내부에 조건이 잘못되어있어서 수정했습니다!
-

#506 [fix] 댓글 삭제 권한 수정

---

module-api/src/main/java/com/mile/common/interceptor/MoimAuthInterceptor.java
module-api/src/test/java/com/mile/common/CorsTest.java

- Closes #516
1. 로컬에서 데브나, 현재 로컬로 테스트해볼 때 에러가 발생하지 않아서 이유를 모르겠어 우선 작성해봤습니다!
-

[feat] interceptor에서 OPTIONS 확인 로직 추가

---

module-domain/src/main/java/com/mile/curious/repository/CuriousRepositoryCustomImpl.java

#527 [hotfix] 모임별 베스트 글모임 산정 방식 변경

---

module-api/src/main/java/com/mile/config/WebConfig.java

#536 [feat] cors dev url 추가

---

module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
module-external/src/main/java/com/mile/aws/utils/S3Service.java

- Closes #539 
1. 기존에 토큰 만료 기간이 너무 짧았어서 이를 연장했습니다.
-

#539 [feat] 토큰 만료 기간 연장

---

module-api/src/main/java/com/mile/common/auth/JwtTokenProvider.java
module-external/src/main/java/com/mile/aws/utils/S3Service.java

#541 [release] 1.1.2 릴리즈

---

module-external/src/main/java/com/mile/aws/utils/S3Service.java

#544 [feat] presigned url 만료시간 연장

---

module-domain/src/main/java/com/mile/moim/service/MoimService.java

#555 [fix] 글모임 권한 확인 관련 로직 수정

---

module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoService.java

#558 [fix] Cache 동시성 이슈 해결

---

module-domain/src/main/java/com/mile/moim/domain/popular/MoimCuriousPost.java
module-domain/src/main/java/com/mile/moim/domain/popular/MoimCuriousWriter.java
module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoService.java

#561 [fix] Cache 동시성 이슈 해결

---

module-api/src/main/java/com/mile/controller/external/InternalController.java
module-domain/src/main/java/com/mile/common/CacheService.java
module-domain/src/main/java/com/mile/moim/domain/popular/MoimPopularInfo.java
module-domain/src/main/java/com/mile/moim/repository/MoimPopularInfoRepository.java
module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoService.java
module-domain/src/main/java/com/mile/post/service/dto/request/PostPutRequest.java
module-external/build.gradle
module-external/src/main/java/com/mile/slack/module/SendMessageModule.java
module-external/src/main/java/com/mile/slack/module/SendWebhookMessage.java

- Closes #569
1. 글모임 인기 정보 관련 삭제 모듈 및 캐시 삭제 API 구현
-

#569 [feat] 글모임 인기 정보 관련 삭제 모듈 및 캐시 삭제 API 구현

---

module-domain/src/main/java/com/mile/common/CacheService.java
module-domain/src/main/java/com/mile/moim/service/lock/AtomicMoimPopulerInfo.java
module-domain/src/main/java/com/mile/moim/service/lock/MoimPopularInfoAspect.java
module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoRegister.java
module-domain/src/main/java/com/mile/moim/service/popular/MoimPopularInfoService.java

- Closes #572 
1. 캐시를 삭제할 수 있는 스케줄러 메서드 구현
2. 삭제시 알람 가도록 구현
3. 분산락 어노테이션 위치 변경
-

#572 [feat] 글모임 캐시 삭제 시 알림 모듈 설계 및 분산락 위치 변경

---

module-api/src/main/java/com/mile/exception/handler/GlobalExceptionHandler.java
module-domain/src/main/java/com/mile/common/CacheService.java
module-external/src/main/java/com/mile/slack/module/SendErrorModule.java
module-external/src/main/java/com/mile/slack/module/SendWebhookMessage.java

- Closes #578 
1. 메신저 이관으로 메시지 전송 모듈 구현
-

#578 [feat] 메신저 이관으로 메시지 전송 모듈 구현

---

module-api/src/main/java/com/mile/common/interceptor/MoimAuthInterceptor.java

#588 [feat] 인가 검증 로직 추가

---

module-api/src/main/java/com/mile/config/WebConfig.java

#594 [feat] dev-local url cors open

---

.github/workflows/PROD-NEW-CD.yml
docker-compose.yml

#576 [feat] 서버 이관 및 docker-compose 배포 방식 구현
- Closes #536
1. 내용
- 설명
-

new prod release

---

module-domain/src/main/java/com/mile/post/service/dto/request/TemporaryPostCreateRequest.java

- Closes #603 
- 내용 최대 글자 수정
-

#603 [feat] 내용 최대 글자 수정

---

.github/workflows/DEV-CD.yml
.github/workflows/PROD-V2-CD.yml
Dockerfile.dev
Dockerfile.prod
module-domain/src/main/java/com/mile/writername/service/WriterNameService.java

#605 [feat] docker file 정리
